### ISSUE TITLE
Parts List

### ISSUE THREAD

**Issue by drewfowler** [jimmerricks/chocolad#2]
Hello Jim! This board looks amazing and I really want to build it. Any chance you have a parts list so that I can order parts before I just order PCBs?

**Comment by KostkaBrukowa** [comment]
I looked into the schema and I think you will need: ​
PCB | 2 pieces |  
Pro Micro | 2 |  
TRRS Jack | 2 |  
Tactile switch | 2 pieces |  
Diode | 36 pieces | Compatible with chip components only
Key switch | 36 pieces | Compatible with Choc (low profile) only
Key-caps | 36 | 1u 
OLED module | 2 pieces |  Optional
4 pin headers | 2 |  
4 pin sockets | 2 |  
Cushion rubber | 8 pieces |  
TRS (3 pole) cable | 1 | TRRS (4 pole) cable also available
Micro USB Cable

Taken from here: https://github.com/foostan/crkbd/blob/main/corne-chocolate/doc/buildguide_en.md
Only thing I don't know its if the board uses SK6812MINI or SK6812MINI-e

**Comment by jimmerricks** [comment]
Thanks Kostka. This looks right. I will add a few notes towards a long ago promised BOM and build guide.

The PCBs are reversible and can be ordered cheaply from JLCPCB or for free from AllPCB (as part of a currently running promotion). The switch and base plates are similarly reversible, but are optional. I have found 1.2mm thickness to work well for them. You may have to pay a surcharge to have the switch plate printed by JLCPCB. OLED covers (also optional) are the same as those for the Corne (which can be ordered or cut from a few places), but it's a tight fit.

The diode type is 1N4148W with the SOD123 package. These are smallish, surface mount components, which need to be mounted with the cathode (usually a thin line) on the side of the square. If you haven't soldered SMT components before, don't worry, it is not too hard. Just make sure you have a decent soldering iron and a decent lead-based solder. The TRRS jacks (PJ-320A) and reset switches (2 pin DIP switches) are through hole components and dead easy to solder.

Pro micros or any alternative (elite-c, nice!nano, etc) will work. These can be mounted facing upwards or downwards. Just make sure that the TX pin goes in the TX hole on the PCB. Be careful here. These are very hard to desolder. Socketing is always a good option, not least because it makes them easier to reuse.

OLEDs (2x SSD1306 128X32) and LEDs (36x SK6812MINI-e) are optional. If you use OLEDs, bridge the jumpers on the top of the board. Again, these are hard to desolder, so may be worth socketing. The LEDs are the trickiest thing to solder in the build. They are mounted in a downwards facing direction on the bottom of the PCB, so that they shine up through the board and through the switch. Do line up the chamfer with the square. Do use liberal amounts of solder flux. Don't use a soldering iron temperature above 300C. Don't hold your iron on the LED leg for more than a second.

Switches are Kailh Chocs (1350). They are tightly spaced so won't work with all Choc stem keycaps. I recommend MBK profile.

Finally, if you do go with plates, you will need 10x 4mm M2 spacers and 20x 3mm M2 screws. Bumpons are also nice, but people use all kinds of things.

The [Corne build guide](https://github.com/foostan/crkbd/blob/main/corne-chocolate/doc/buildguide_en.md) is good. Also check out the guide for the [Sofle](https://josefadamcik.github.io/SofleKeyboard/) and, for the LEDs, the [YAEMK](https://karlk90.github.io/yaemk-split-kb/#correct-orientation-of-rgb-leds) guide is handy.

**Comment by jimmerricks** [comment]
Alternatively, I have a kit or two left over if you want one.

**Comment by drewfowler** [comment]
Thanks for the response. I ordered everything earlier today and did standard 1.6mm for pcbs. So we will see how they turn out. 
I appreciate the help and am looking forward to building it!

**Comment by jimmerricks** [comment]
No worries. Please send me a picture when you are done and I hope that you enjoy the keyboard.
